# Generated by Django 4.1 on 2022-08-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(default='', max_length=6, unique=True)),
                ('host', models.CharField(max_length=20, unique=True)),
                ('user_count', models.IntegerField()),
                ('can_play', models.BooleanField(default=False)),
                ('can_pause', models.BooleanField(default=False)),
                ('can_queue', models.BooleanField(default=False)),
                ('skip_votes', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
