# Generated by Django 4.1 on 2022-08-19 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobby',
            old_name='created_at',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='lobby',
            old_name='user_count',
            new_name='lobby_count',
        ),
    ]
