# Generated by Django 4.1 on 2022-08-28 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_lobby_lobby_count_alter_lobby_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='can_play',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='can_queue',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='lobby_count',
        ),
    ]
